### ISSUE TITLE
config file: typo in uuid

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AirInterfacePowerSaver#100]
In [config.json](https://github.com/openBackhaul/AirInterfacePowerSaver/blob/develop/spec/AirInterfacePowerSaver%2Bconfig.json) file, the uuid for tcp-client of AirInterfacePowerSaver shall be aips-0-0-5-tcp-c-aips-0-0-5-000. But it is present as ps-0-0-5-tcp-c-aips-0-0-5-000. This shall be changed

**Comment by kmohr-soprasteria** [comment]
will be corrected and updated to v0-0-10
