### ISSUE TITLE
Request to remove FileProfile related OAM layer services from OAS 

### ISSUE THREAD

**Issue by at00825957** [openBackhaul/AirInterfacePowerSaver#104]
As per understanding , file-profile contains the file details where we store application specific data.

In current AirInterfacePowerSaver application, application specific data is being stored in elastic search and also there is no file-profile related data in config.json.

Proposal :
Can we remove file profile from AirInterfacePowerSaver as there is no application specific data we are storing in file.

Changes required (If above proposal is accepted) :

To remove file profile related OAM Layer services from OAS of AirInterfacePowerSaver application.

**Comment by kmohr-soprasteria** [comment]
will be needed from v009+ on.
