### ISSUE TITLE
Request to remove IntegerProfile related OAM layer services from OAS

### ISSUE THREAD

**Issue by at00825957** [openBackhaul/AirInterfacePowerSaver#105]
In current AirInterfacePowerSaver application, there is no integer-profile related data in config.json, so assumption is integer-profile is not used in the application.

Proposal :
Can we remove integer-profile from AirInterfacePowerSaver as we are not using it anywhere in the application.

Changes required (If above proposal is accepted) :

To remove integer-profile related OAM Layer services from OAS of AirInterfacePowerSaver application.

**Comment by kmohr-soprasteria** [comment]
done with v009 spec
