### ISSUE TITLE
forwardings.yaml file: few uuids are missing in INPUT port of ServiceRequestCausesLoggingRequest

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AirInterfacePowerSaver#72]
In [forwardings.yaml ](https://github.com/openBackhaul/AirInterfacePowerSaver/blob/develop/spec/AirInterfacePowerSaver%2Bforwardings.yaml) file, we have a forwarding _ServiceRequestCausesLoggingRequest_. 

here, the "initiating-requests" is missing with following services
- /v1/receive-power-saving-activation-status ( aips-0-0-5-op-s-is-405 )
- /v1/receive-power-saving-deactivation-status ( aips-0-0-5-op-s-is-415 )
- /v1/receive-transmitter-status-of-parallel-links ( aips-0-0-5-op-s-is-501 )

These needs to be added. 
Note: The entries are present in config.json file in _ServiceRequestCausesLoggingRequest_ forwarding

**Comment by kmohr-soprasteria** [comment]
has already been resolved.
