### ISSUE TITLE
MWDI release-number shall be updated to 1.1.1

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AirInterfacePowerSaver#74]
As per issue https://github.com/openBackhaul/AirInterfacePowerSaver/issues/63, we could find that the compatible version of MicroWaveDeviceInventory (MWDI) to AIPS (AirInterfacePowerSaver) is MWDI v1.1.1 (which is the latest tag).

So, based on MWDI release-number 1.1.1, the uuid and release-number attributes in MWDI shall need to be updated in [OAS file](https://github.com/openBackhaul/AirInterfacePowerSaver/blob/develop/spec/AirInterfacePowerSaver.yaml), [config.json file](https://github.com/openBackhaul/AirInterfacePowerSaver/blob/develop/spec/AirInterfacePowerSaver%2Bconfig.json),[ forwardings.yaml file](https://github.com/openBackhaul/AirInterfacePowerSaver/blob/develop/spec/AirInterfacePowerSaver%2Bforwardings.yaml), [services.yaml file](https://github.com/openBackhaul/AirInterfacePowerSaver/blob/develop/spec/AirInterfacePowerSaver%2Bservices.yaml) files.

- the uuid(s) shall be updated from mwdi-1-0-1 to mwdi-1-1-1 in all the above mentioned files in all occurrence
- the release-number of MWDI client shall be updated from "1.1.0" to "1.1.1" in config.json and services.yaml file

**Comment by kmohr-soprasteria** [comment]
already resolved
