### ISSUE TITLE
duplicate entries of operation-clients of client applications

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AirInterfacePowerSaver#75]
For the client application MicroWaveDeviceInventory, we could see three operation-client ltp instances for same operation-name _/core-model-1-4:network-control-domain=cache/link={uuid}_ which are aips-0-0-5-op-c-is-mwdi-1-0-1-500, aips-0-0-5-op-c-is-mwdi-1-0-1-510 and aips-0-0-5-op-c-is-mwdi-1-0-1-602. 

This creates duplicate entries for the same operation-name **which could be reduced to one operation-client and reused in all places wherever required**. 
- Similarly for other client applications, the following operations are duplicated.
    - For MicroWaveDeviceGatekeeper, the same operation-name _/core-model-1-4:network-control-domain=live/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/air-interface-2-0:air-interface-pac/air-interface-configuration/transmitter-is-on_ has two duplicate operation-client instances (aips-0-0-5-op-c-is-mwdg-1-0-0-500 and aips-0-0-5-op-c-is-mwdg-1-0-0-510)
    - For AirInterfacePowerSaver client, two duplicate operation-client instances are present for _/v1/record-power-saving-status_ (aips-0-0-5-op-c-is-aips-0-0-5-501 and aips-0-0-5-op-c-is-aips-0-0-5-511). 

The above changes shall be required to be made 
- in [OAS file](https://github.com/openBackhaul/AirInterfacePowerSaver/blob/develop/spec/AirInterfacePowerSaver.yaml) and [ forwardings.yaml file](https://github.com/openBackhaul/AirInterfacePowerSaver/blob/develop/spec/AirInterfacePowerSaver%2Bforwardings.yaml), 
    - the duplicated entries shall be updated with the actual finalized uuid of operation-client
- [config.json file](https://github.com/openBackhaul/AirInterfacePowerSaver/blob/develop/spec/AirInterfacePowerSaver%2Bconfig.json) , 
   - the duplicate operation-clients shall be removed from logical-termination-point  
   - removed uuid(s) shall be deleted from client-ltp list of http-c instance of respective applications
   - the duplicated entries shall be updated with the actual finalized uuid of operation-client in forwardings
-  [services.yaml file](https://github.com/openBackhaul/AirInterfacePowerSaver/blob/develop/spec/AirInterfacePowerSaver%2Bservices.yaml) file , the duplicate operation-clients shall be removed from service list of respective applications

**Comment by kmohr-soprasteria** [comment]
The duplicate operation-clients shall be kept. 
They were introduced on purpose: each module uses it's own instance of the respective operation-client to simplify the modularization. (E.g. if we want to apply a change to some module with respect to a certain operation-client, it won't affect other modules)
