### ISSUE TITLE
Requesting clarification regarding the version of TAC applications. 

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AirInterfacePowerSaver#76]
In specification of AirInterfacePowerSaver (AIPS), we could see that all the TAC applications are defined with release-number = 2.0.2. 

Since the latest version of TAC applications available is 2.0.1, could you please let us know if this is fine to point towards 2.0.2 version of TAC applications from AIPS.  Kindly correct me if I am missing any points to understand here.

On the other hand, if it is fine that version of TAC applications could be 2.0.2, then the following files needs few update.

- In [config.json](https://github.com/openBackhaul/AirInterfacePowerSaver/blob/develop/spec/AirInterfacePowerSaver%2Bconfig.json) file :: the OUTPUT fc-port of forwarding ServiceRequestCausesLoggingRequest shall be updated from aips-0-0-5-op-c-bs-eatl-2-0-1-000 to _aips-0-0-5-op-c-bs-eatl-2-0-2-000_
- In [forwardings.yaml ](https://github.com/openBackhaul/AirInterfacePowerSaver/blob/develop/spec/AirInterfacePowerSaver%2Bforwardings.yaml) file, the operation-client uuid(s) of RegistryOffice shall be updated from ro-2-0-1 to _ro-2-0-2_
- In [OAS](https://github.com/openBackhaul/AirInterfacePowerSaver/blob/develop/spec/AirInterfacePowerSaver.yaml) file, the operation-client uuid(s) of RegistryOffice shall be updated from ro-2-0-1 to _ro-2-0-2_ (especially in all callback url(s) of /v1/bequeath-your-data-and-die)

Related issue : https://github.com/openBackhaul/MicroWaveDeviceGatekeeper/issues/16

**Comment by PrathibaJee** [comment]
Please look into the decision in the issue https://github.com/openBackhaul/MicroWaveDeviceGatekeeper/issues/16.
Closing this issue.
