### ISSUE TITLE
uuid of operation-client(s) requires changes for release-number placeholder

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AirInterfacePowerSaver#98]
Since, the release-number of TAC applications are expected to be 2.0.2, the following needs changes in uuid for release-numbers :

- In [config.json](https://github.com/openBackhaul/AirInterfacePowerSaver/blob/develop/spec/AirInterfacePowerSaver%2Bconfig.json) file :: the OUTPUT fc-port of forwarding ServiceRequestCausesLoggingRequest shall be updated from aips-0-0-5-op-c-bs-eatl-2-0-1-000 to aips-0-0-5-op-c-bs-eatl-2-0-2-000
- In [forwardings.yaml ](https://github.com/openBackhaul/AirInterfacePowerSaver/blob/develop/spec/AirInterfacePowerSaver%2Bforwardings.yaml)file, the operation-client uuid(s) of RegistryOffice shall be updated from ro-2-0-1 to ro-2-0-2
- In [OAS](https://github.com/openBackhaul/AirInterfacePowerSaver/blob/develop/spec/AirInterfacePowerSaver.yaml) file, the operation-client uuid(s) of RegistryOffice shall be updated from ro-2-0-1 to ro-2-0-2 (especially in all callback url(s) of /v1/bequeath-your-data-and-die)

Reference issues: https://github.com/openBackhaul/MicroWaveDeviceGatekeeper/issues/16 and https://github.com/openBackhaul/AirInterfacePowerSaver/issues/76

**Comment by kmohr-soprasteria** [comment]
handled in #125

**Comment by kmohr-soprasteria** [comment]
updated TAC version numbers/uuids to 2-1-0
